# Generated by Django 4.2.6 on 2023-10-08 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('AdminStaff', '0001_initial'),
        ('SupportTicket', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('FeedbackID', models.BigAutoField(primary_key=True, serialize=False)),
                ('AdminName', models.CharField(max_length=50)),
                ('Contents', models.CharField(max_length=500)),
                ('AdminID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Adminfeedbacks', to='AdminStaff.adminstaff')),
                ('TicketID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='DonorTicket', to='SupportTicket.supportticket')),
            ],
        ),
    ]
