# Generated by Django 4.2.6 on 2023-10-08 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Beneficiary', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='beneficiary',
            old_name='PasswordHash',
            new_name='Password',
        ),
    ]
