# Generated by Django 4.2.6 on 2023-10-08 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Beneficiary', '0002_rename_passwordhash_beneficiary_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiary',
            name='Needs',
            field=models.CharField(choices=[('food', 'Food'), ('clothing', 'Clothing'), ('shelter', 'Shelter'), ('education', 'Education'), ('medical', 'Medical'), ('utilities', 'Utilities'), ('transportation', 'Transportation'), ('employment', 'Employment'), ('other', 'Other')], default='food', max_length=50),
        ),
    ]
