# Generated by Django 4.2.6 on 2023-10-10 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Beneficiary', '0004_beneficiary_amounttrackerid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiary',
            name='Username',
            field=models.CharField(default='', max_length=30),
        ),
    ]
