# Generated by Django 4.2.6 on 2023-10-08 05:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Donor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dik',
            name='GDID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Donor.goodsdetails'),
        ),
    ]
