# Generated by Django 4.2.6 on 2023-10-09 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Donor', '0005_alter_amount_tracker_table_alter_cashdetail_table_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='amount_tracker',
            table='Amount tracker',
        ),
        migrations.AlterModelTable(
            name='cashdetail',
            table='Cash Details',
        ),
        migrations.AlterModelTable(
            name='currency',
            table='Currency',
        ),
        migrations.AlterModelTable(
            name='dik',
            table='Donation in Kind',
        ),
        migrations.AlterModelTable(
            name='donor',
            table='Donor',
        ),
        migrations.AlterModelTable(
            name='goods_tracker',
            table='Goods tracker',
        ),
        migrations.AlterModelTable(
            name='goodsdetail',
            table='Goods Details',
        ),
    ]
