# Generated by Django 4.2.6 on 2023-10-09 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Donor', '0006_alter_amount_tracker_table_alter_cashdetail_table_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashdetail',
            name='DonorID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cash_details', to='Donor.donor'),
        ),
    ]
