# Generated by Django 4.2.6 on 2023-10-08 06:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('AdminStaff', '0001_initial'),
        ('Donor', '0003_alter_dik_diktype'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('adminstaff_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='AdminStaff.adminstaff')),
                ('TicketID', models.BigAutoField(primary_key=True, serialize=False)),
                ('Contents', models.CharField(max_length=500)),
                ('ConfirmationType', models.CharField(choices=[('approved', 'Approved'), ('rejected', 'Rejected'), ('pending', 'Pending')], max_length=12)),
                ('AdminID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_tickets', to='AdminStaff.adminstaff')),
                ('DonorID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Donor.donor')),
            ],
            options={
                'abstract': False,
            },
            bases=('AdminStaff.adminstaff',),
        ),
    ]
